# Uncomment this line to define a global platform for your project
platform :ios, '7.1'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking', '~> 3.0'

target 'WeatherTM' do

end

target 'WeatherTMTests' do

end

target 'WeatherTMUITests' do

end

